services:
  proxy: 
    image: "traefik:2.6"
    container_name: "traefik"
    command: 
      - "--api.insecure"
      - "--providers.docker"
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

networks:
  default:
    name: proxy