volumes:
  gif-db: {}
services:
  app:
    image: node:16-alpine
    command: npm run dev
    working_dir: /usr/local/app
    volumes:
      - ./mongo-config-sample.json:/run/secrets/mongo-config.json
      - ./:/usr/local/app
    ports:
      - 3000:3000
    environment:
      CUSTOM_MESSAGE: Take care of your ENVIRONMENT
      MONGO_CONFIG_FILE: /run/secrets/config.json
  mongo:
    image: mongo:5.0
    volumes:
      - gif-db:/data/db
  mongo-express:
    image: mongo-express
    depends_on: 
      - mongo
    ports:
      - "8081:8081"
secrets:
  config.json:
    external: true;
    
