version: "3.8"
volumes:
  gif-db: {}
services:
  app:
    image: danderson11235/gif-collection
    ports:
      - 3000:3000
  mongo:
    image: mongo:5.0
    volumes:
      - gif-db:/data/db
  mongo-express:
    image: mongo-express
    depends_on: 
      - mongo
    ports:
      - "8081:8081"
    
    
