volumes:
  gif-db: {}

networks:
  proxy: 
    external: true
    name: proxy
  random-gif:
    external: false
    name: random-gif

services:
  mongo:
    image: mongo:5.0
    volumes:
      - gif-db:/data/db
    networks:
      - random-gif
  app:
    image: danderson11235/random-gif2
    networks:
      - random-gif
      - proxy
    labels: 
      - traefik.http.routers.app.rule=Host(`app.localhost`)
      - traefik.http.services.app.loadbalancer.server.port=3000
  mongo-express:
    image: mongo-express
    depends_on: 
      - mongo
    networks:
      - random-gif
      - proxy
    labels:  
      - traefik.http.routers.mongo.rule=Host(`mongo.localhost`)
      - traefik.http.services.mongo.loadbalancer.server.port=8081
    